services:
  gitlab:
    image: gitlab/gitlab-ce:18.2.0-ce.0
    container_name: gitlab
    restart: always
    hostname: ${GITLAB_DOMAIN}
    environment:
      VIRTUAL_HOST: ${GITLAB_DOMAIN}
      LETSENCRYPT_HOST: ${GITLAB_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_DOMAIN}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${GITLAB_SSH_PORT}
        nginx['enable'] = true
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = false
        letsencrypt['enable'] = false

        registry['enable'] = true
        registry_external_url "https://registry.${GITLAB_DOMAIN}"
        gitlab_rails['registry_enabled'] = true

        registry_nginx['enable'] = true
        registry_nginx['listen_port'] = 5050
        registry_nginx['listen_https'] = false
    expose:
      - "80"
      - "5050"
    ports:
      - "${GITLAB_SSH_PORT}:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    shm_size: '256m'
    networks:
      - nginx_proxy-tier

  gitlab-runner:
    image: gitlab/gitlab-runner:v18.2.0
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-config:

networks:
  nginx_proxy-tier:
    external: true